name: dipikul websocket api

on:
  push:
      branch:
        - development

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-20.04
    environment: development
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
    - name: Create env file
      run: |
        touch .env
        echo NODE_ENV=${NODE_ENV} >> .env
        echo STAGE=${STAGE} >> .env
        echo PUBLISH_ENDPOINT=${PUBLISH_ENDPOINT} >> .env
        echo REGION=${REGION} >> .env
        echo TOPICS_TABLE=${TOPICS_TABLE} >> .env
        echo EVENTS_TABLE=${EVENTS_TABLE}  >> .env
        cat .env
      env:
        NODE_ENV: ${{ secrets.NODE_ENV }}
        STAGE: ${{ secrets.STAGE }}
        PUBLISH_ENDPOINT: ${{ secrets.PUBLISH_ENDPOINT }}
        REGION: ${{ secrets.REGION }}
        TOPICS_TABLE: ${{ secrets.TOPICS_TABLE }}
        EVENTS_TABLE: ${{ secrets.EVENTS_TABLE }}
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}